name: Create Issue Comments

on:
  push:
    branches:
      - main  # Die Haupt-Branch anpassen, falls benötigt

jobs:
  create_comments:
    runs-on: ubuntu-latest

    steps:
      - name: Get changed files
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
          echo "Test ${changed_file}."
          done

      - name: Create Issue Comments
        uses: peter-evans/create-or-update-comment@v3
        
#        if: |
#          contains(github.event.comment.body, '/gpt-translate') || 
#          contains(github.event.comment.body, '/gt')
          
        with:
          issue-number: 3
          body: |
            /gpt-translate ${changed_file} /DE/${changed_file} German
            /gpt-translate ${changed_file} /IT/${changed_file} Italian
            /gpt-translate ${changed_file} /FR/${changed_file} French
