name: PoC script

on:
  push:
    branches:
      - main  # Change to the branch you want to trigger the action on

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  execute-script:
    runs-on: ubuntu-latest  # Choose the operating system you prefer

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute script
      run: |
        chmod +x PoC/script.sh
        ./PoC/script.sh
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
