name: Create Issue Comments

on:
  push:
    branches:
      - main  # Die Haupt-Branch anpassen, falls benötigt

jobs:
  create_comments:
    runs-on: ubuntu-latest

    steps:
      - name: Get changed files
        id: changed_files
        run: echo "name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: Create Issue Comments
        if: contains(github.event_name, 'push')
        run: |
          for changed_file in ${{ steps.changed_files.outputs.files }}          
          echo "/gpt-translate $changed_file /DE/$changed_file german" | gh issue create-comment ${{ github.repository }} ${{ github.event.issue.number }}
          echo "/gpt-translate $changed_file /IT/$changed_file italian" | gh issue create-comment ${{ github.repository }} ${{ github.event.issue.number }}
          echo "/gpt-translate $changed_file /FR/$changed_file french" | gh issue create-comment ${{ github.repository }} ${{ github.event.issue.number }}
