name: Create Issue Comments

on:
  push:
    branches:
      - main  # Die Haupt-Branch anpassen, falls benötigt

jobs:
  create_comments:
    runs-on: ubuntu-latest

    steps:
      - name: Get changed files
        id: changed_files
        run: echo "name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: Create Issue Comments
        uses: peter-evans/create-or-update-comment@v3
        
        with:
          issue-number: 3
          body: |
            for changed_file in ${{ steps.changed_files.outputs.files }}           
            /gpt-translate $changed_file /DE/$changed_file German
            /gpt-translate $changed_file /IT/$changed_file Italian
            /gpt-translate $changed_file /FR/$changed_file French
