name: PoC script

on:
  push:
    branches:
      - main  # Change to the branch you want to trigger the action on

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  execute-script:
    runs-on: ubuntu-latest  # Choose the operating system you prefer

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Get changes
      id: changed-files
      run: |
        echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
    
    - name: List changes files and
      run: |
        curl www.google.com

        for file in ${{ steps.changed-files.outputs.changed_files }}; do
            cat $file
        done



    # Runs a single command using the runners shell
   # - name: Run a one-line script
   #   run: echo Hello, world!
